### PR TITLE
Release version 3.0.0

### PR DESCRIPTION
**Pull request by chrisalley**

### CODE REVIEW

**Comment by chrisalley** [comment]
Based on my testing, this is ready for release.

**Comment by chrisalley** [comment]
Is this release ready to be approved @tagliala?

**Comment by tagliala** [comment]
@chrisalley at this point I would say no

We have problem similar to the one described in #98 with `permit_action`, if used with an array.

In other words, 

```rb
      it { is_expected.to permit_action(%i[test test2]) }
```

this is allowed and the spec will pass

A solution is possible. Even trivial for `permit_action`, but it is not trivial for `permit_attribute` with nested parameters. I will try to work on that

**Comment by chrisalley** [comment]
For now, fixing `permit_action`/`forbid_action` to be limited to one action (and add tests for this) would be sufficient to get the release finalised.

**Review by tagliala — APPROVED** [review]

**Pull request merged**
