### PR TITLE
Introduce Test Policy

### PR DESCRIPTION
**Pull request by tagliala**
This will allow to test matcher error messages

### CODE REVIEW

**Comment by tagliala** [comment]
Almost 100%, also found a couple of improvements to messages

**Comment by tagliala** [comment]
I cannot understand if it is possible to have a negated message failure for 
- forbid_actions
- permit_actions
- forbid_mass_assignment_of
- permit_mass_assignment_of

without arguments

**Comment by tagliala** [comment]
Blocked by #57

**Comment by tagliala** [comment]
Now blocked by #66

**Comment by tagliala** [comment]
```
Coverage report generated for RSpec to /Users/geremia/dev/pundit-matchers/coverage. 362 / 366 LOC (98.91%) covered.
```

The only four lines that I wasn't able to test are related to empty arrays and the negated matcher

**Comment by chrisalley** [comment]
Excellent work. We're now in a much better position when it comes to code coverage, which will make future improvements to the implementation safer.

Based on the discussion in #30, I think we were in agreement about disabling negated matchers as way of simplifying the implementation, unless there's a better proposal.

**Comment by tagliala** [comment]
Ah, it was easy

```
return false if attributes.count < 1
```

With a negated matcher, this will return true and so there should not be the possibility to have that error with a negated matcher

**Pull request merged**
