### PR TITLE
[WIP] Introduce Dummy Policy

### PR DESCRIPTION
**Pull request by tagliala**
This will allow to test matcher error messages

---

I've noticed that error messages are not test, so it would be a risk to fix rubocop offences in `lib/pundit/matchers.rb`

Once we get 100% coverage, we can refactor offenses 

Please let me know if you want me to continue on this PR

### CODE REVIEW

**Comment by tagliala** [comment]
I wasn't able to find a configuration to trigger this message:

https://github.com/punditcommunity/pundit-matchers/blob/9fe6621abbc1ebf1f5cf2bbc54511ee3767c6ac6/lib/pundit/matchers.rb#L75

**Comment by chrisalley** [comment]
This looks like a good change, and I agree it's worthwhile to aim for 100% test coverage. If we could rename the policy from `DummyPolicy` to `TestPolicy` to [avoid any controversy](https://english.stackexchange.com/questions/269160/is-the-word-dumb-offensive/269258#269258) that would be great.

**Comment by chrisalley** [comment]
> I wasn't able to find a configuration to trigger this message:
> 
> https://github.com/punditcommunity/pundit-matchers/blob/9fe6621abbc1ebf1f5cf2bbc54511ee3767c6ac6/lib/pundit/matchers.rb#L75

I think the intent was that if you call `forbid_actions([])` the error will appear.

**Comment by tagliala** [comment]
> > I wasn't able to find a configuration to trigger this message:
> > https://github.com/punditcommunity/pundit-matchers/blob/9fe6621abbc1ebf1f5cf2bbc54511ee3767c6ac6/lib/pundit/matchers.rb#L75
> 
> I think the intent was that if you call `forbid_actions([])` the error will appear.

I've tried without success. Because it's the negated message, so if you pass an empty array it looks like it is unable to raise 🤷🏻‍♂️

BTW i will open a new request because I've also changed the branch name

**Pull request closed without merging**
