### PR TITLE
Minor improvements to Policy Info

### PR DESCRIPTION
**Pull request by tagliala**
- Add YARD documentation
- Memoize forbidden actions for parity with permitted actions
- Use attribute accessor to access `policy`
- Move public policy methods to a memoized private method

---

May not look immediate why, but this is going to help in implementing #24 (and improve the attribute matcher class)

We can have something like

```rb
def permitted_attributes_actions
  @permitted_attributes_actions ||= public_policy_methods.grep(/\Apermitted_attributes(_for_.+)?\z/).sort
end
```

### CODE REVIEW

**Comment by chrisalley** [comment]
What are your thoughts on adding RBS to this project as well as YARD documentation?

adding https://github.com/ruby/rbs

**Comment by chrisalley** [comment]
RBS code lives in a seperate file but the signatures can be tested . This would be a development dependency with tests that could go through CI:

https://github.com/ruby/rbs/blob/master/docs/sigs.md#testing-signatures

**Comment by chrisalley** [comment]
I've merged this. I'll open a seperate issue to discuss adding type signatures more broadly.

**Comment by tagliala** [comment]
Type signatures are interesting and I would like to experiment. Since this gem is small, I think that it could be worth to make an attempt.

Now I think I'm almost ready to submit the classes refactor.

We need to agree on some things there

- [ ] Loading of individual classes
- [ ] Expectation messages (I'm not an English native speaker). They have been slightly changed, and they are now uniform. Of course they can be improved, but I've noticed that from a developer point of view `does not permit [:test, :test2, :test3]` is preferrable to `does not permit 'test', 'test2', and 'test3'`
- [ ] We have 100% coverage, but tests are all new. I should "backport" old integration tests to check if I didn't break things (but some specs are already broken, see #78) and then we should remove them

**Comment by tagliala** [comment]
> The main thing we need to ensure is the that matchers API defined in the Readme remains the same for backward compatibility (so that people don't need to spend time rewriting their tests). 

I'll be back on this and provide a clear comparison table during the weekend. In the meanwhile, you can start reviewing error messages

My plan is to: 
- Temporarily reintroduce a "legacy" folder in specs with all legacy specs. Legacy specs will be merged together with the refactor, and removed in a later PR
- Provide a comparison table of what is going to change (example: `not_to forbid_all` will raise)
- Some things will break, just because of the bugfix being introduced (like #30)

I'm testing this refactor on a codebase with 300+ policy related specs, and the only thing that break was a misusage of nested attributes

**Pull request merged**
