### PR TITLE
Add `*_only_actions` matchers

### LINKED ISSUE #41: Feature request: `permit_only_*` matcher
Hi,

apologies if this is a duplicate or if this is already possible, but I wasn't able to find a solution

In the effort of improving security and mitigate A01:2021-Broken Access Control issues, would it be possible to have a `permit_only` matcher?

At the moment I'm now using a custom approach that:

1. Defines all actions in the policy
2. Checks that the forbids `all_actions - permitted_actions`
3. Checks that the policy permits `permitted_actions` (if any left)

However, this approach has the limitation that a developer may forgot to add new actions to the spec file, so there is no guarantee that the new action is forbidden by default

I've improved the custom approach by creating a helper that uses `PolicyInfo`'s model to automatically get all the actions in a policy, but I think that having a built-in matcher with a better failure message could improve the developer experience

Ref:
- https://owasp.org/Top10/A01_2021-Broken_Access_Control/
- varvet/pundit#711

### PR DESCRIPTION
**Pull request by tagliala**
Hi, this is a prototype of the feature described in #41

Please let me know what do you think

TODO:
- [x] Readme
- [x] Forbid only
- [ ] Readme section (with explanation of  A01:2021-Broken Access Control)

Close #41

### CODE REVIEW

**Comment by chrisalley** [comment]
I like your direction/approach. This can be reviewed/merged once the readme updates and `forbid_only_actions` matcher are complete.

**Comment by iainbeeston** [comment]
@tagliala Is there any chance of finishing this? I'd like to use it too. Is there anything I can do to help?

**Comment by tagliala** [comment]
Hi, I'm still interested in developing this feature

I had some busy weeks and took some time off. I can take a look during the weekend, but I can't promise

@iainbeeston if you have some free time to continue right now, please just let me know and feel free to fork my branch

**Comment by iainbeeston** [comment]
@tagliala I had a quick look but I'm not sure how I'd to the forbidden version using the same classes. I could help with the readme? However, I won't have any time to look at this until next week.

**Comment by tagliala** [comment]
I've added `forbid_only_actions` and a couple of entries in the readme

I do not like this approach entirely, because there is a lot of duplication in specs and will introduce some technical debt, but also I do not have a lot of free time to invest 🥲

I think that a similar option for `permit_mass_assignment` should be used. I was thinking if this can follow [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers) approach, let's say `permit_mass_assignment_of(:name).only`, but that could be done in a new PR

**Comment by iainbeeston** [comment]
The code looks nice to me and I don't think duplication in specs is such a bad thing (in general). I'm not sure if @chrisalley would agree though?

**Comment by chrisalley** [comment]
Since the feature is complete, I think this is ready for code review. I'll get onto that. A bit of duplication can potentially be addressed in a future PR if there is not too much of it.

For attributes, another PR could be opened, but let's discuss any syntax changes in issue #41 first.

**Comment by tagliala** [comment]
Probably another section in the readme is needed, with an explanation on why you should prefer to test this way

**Comment by chrisalley** [comment]
I can review this over the next couple of days and write a section for the Readme.

**Comment by tagliala** [comment]
I have something like this, partially written by ChatGPT

```
+## Mitigate Broken Access Control risk
+
+When it comes to testing for access control vulnerabilities, it is important
+to ensure that only authorized users are able to access and perform certain
+actions within the system. The `permit_only_actions` method provides a simple
+and effective way to test this aspect of access control.
+
+This method allows to specify only the actions that should be permitted
+for a given user, and verifies that all other actions are denied.
+
+```ruby
+require 'rails_helper'
+
+describe ArticlePolicy do
+  subject { described_class.new(user, article) }
+
+  let(:article) { Article.new }
+
+  context 'being a visitor' do
+    let(:user) { nil }
+
+    it { is_expected.to permit_only_actions(%i[show]) }
+  end
+end
```

I think it should be advised as the preferred method to test policies

**Comment by chrisalley** [comment]
Yes, I agree that this approach would make a sensible default. Although it has the downside of being slightly more difficult to understand for newcomers than permit action/actions, from a security standpoint we should recommend the safest approach.

Let's update the readme so that is placed before `permit_action` and `forbid_action` in the lists of matchers and mentioned in "A Basic Example of a Policy Spec".

**Comment by chrisalley** [comment]
The code has been reviewed and merged. We can put through seperate PRs for fixing the Rubocop violations and updating the readme.

**Comment by chrisalley** [comment]
Issues that we need to complete before the next release:

https://github.com/punditcommunity/pundit-matchers/issues/53
https://github.com/punditcommunity/pundit-matchers/issues/54

**Pull request merged**
