### PR TITLE
[WIP] Implement matchers in individual classes

### PR DESCRIPTION
**Pull request by tagliala**
@chrisalley this is an experiment, there are many other things to do

In this refactor, all matchers inherit from "ActionsMatchers", and they are all variant of the same matcher.

- All expectation messages are small customizations of a single message
- `permit_action`/`forbid_action` are variants of `permit_actions`/`forbid_actions` with a single parameter
- `permit_all_actions`, `forbid_all_actions`, `permit_only_actions`, `forbid_all_actions`  use the policy info to make their expectation, they are very simple array comparisons

Also:
- Remove compatibility with Pundit 1.x
- Remove the ability to use negated matchers
- Drop policy with arguments

ToDo:
- [ ] Proper inclusion (check how shoulda matchers does)
- [ ] Mass assignment
- [ ] Proper specs (shared contexts, "behaves like", unit tests, integration tests)
- [ ] Documentation
- [ ] Understand how chaining works

### Before
```
$ git ls-files lib | xargs cloc
      14 text files.
      14 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.96  T=0.01 s (1861.2 files/s, 107283.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Ruby                            14            132             47            628
-------------------------------------------------------------------------------
SUM:                            14            132             47            628
-------------------------------------------------------------------------------
```

### After

```
git ls-files lib | xargs cloc
      11 text files.
      11 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.96  T=0.01 s (1707.5 files/s, 88325.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Ruby                            11            121             14            434
-------------------------------------------------------------------------------
SUM:                            11            121             14            434
-------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by chrisalley** [comment]
As an experiment this looks promising. If we could break this down into smaller PRs that would be more manageable and easier to track any regressions.

At the least, keeping the refactoring (non breaking changes) and dropping support (breaking changes) as separate PRs.

**Comment by tagliala** [comment]
Hi,

I think I've found a better approach that will also allow to properly use negated matchers

It should be enough to provide `forbid_matcher` and a `permit_matcher` methods and alias them as `does_not_match?` and `matches?`

**Comment by chrisalley** [comment]
> It should be enough to provide forbid_matcher and a permit_matcher methods and alias them as does_not_match? and matches? according to the specific matcher

That sounds good; provided we’ve got full test coverage, and you’re happy to make the changes, I think we can support negated matchers.

**Comment by tagliala** [comment]
Action Matchers can be implemented by defining only `permit_action*`, with both `matches?` and `does_not_match?` methods.

Then, `forbid_action*` can be defined as the negated matcher of `permit_action*`.

With this approach:
- negated matches will work as expected
- no code duplication
- no aliases

Ref:

https://github.com/tagliala/pundit-matchers/commit/5635499eb12527ca720a1319969cb790efc2b6fa#diff-a3affd6d629b9ffd752de7759d979d2c0e62d5fd9a4b33a10dad7b70cd8660e7

https://github.com/tagliala/pundit-matchers/commit/5635499eb12527ca720a1319969cb790efc2b6fa#diff-a3fa020c066bb5e51ed11027cf18a65ce7bd673fe955ae75d6481fcfae1c4bf7

**Pull request closed without merging**
